import webbrowser
def searchgoogle():
 print("Çıkış için: 'q'")
 while True:
     search = input("\nGoogle: ")
     if search == "q":
        break
     url = f"https://www.google.com/search?q={search}&sca_esv=7e63893fda4bafb0&sca_upv=1&sxsrf=ACQVn09uW9n4DHl6Gv--82QMIoeJuCek_A%3A1712412524611&ei=bFcRZqfuJPSGxc8Pgu2F2As&udm=&ved=0ahUKEwin1PPh4a2FAxV0Q_EDHYJ2AbsQ4dUDCBA&uact=5&oq=sela&gs_lp=Egxnd3Mtd2l6LXNlcnAiBHNlbGEyChAuGEMYgAQYigUyCxAuGIAEGLEDGIMBMggQLhiABBixAzIIEC4YgAQYsQMyCBAuGLEDGIAEMgsQLhiABBixAxiDATILEAAYgAQYsQMYgwEyCBAAGIAEGLEDMggQABiABBixAzIIEAAYgAQYsQMyGRAuGEMYgAQYigUYlwUY3AQY3gQY3wTYAQNI1BNQ8ANY1wpwAngAkAEAmAG5AaAB3gWqAQMwLjW4AQPIAQD4AQGYAgegAroGqAISwgINEC4YQxiABBiKBRiwA8ICDhAAGIAEGIoFGLEDGLADwgINEAAYgAQYigUYQxiwA8ICCxAAGIAEGLEDGLADwgIIEAAYgAQYsAPCAgoQIxiABBiKBRgnwgIEECMYJ8ICChAAGIAEGIoFGEPCAgUQABiABMICChAuGIAEGIoFGEPCAgcQIxjqAhgnwgITEAAYgAQYigUYQxjqAhi0AtgBAcICFhAuGEMYgAQYigUYyAMY6gIYtALYAQLCAhwQLhiABBiKBRhDGMcBGNEDGMgDGOoCGLQC2AECwgIQEC4YgAQYigUYQxixAxiDAcICBRAuGIAEwgIOEAAYgAQYigUYsQMYgwHCAg4QLhiABBiKBRixAxiDAZgDEIgGAZAGCroGBggBEAEYAboGBggCEAEYCLoGBggDEAEYFJIHBTIuNC4xoAf1YQ&sclient=gws-wiz-serp"
     webbrowser.open(url)
